// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATll02SFjiYq75OUQfrsnezTqeBxDnzDY',
    appId: '1:1040924011798:web:dff84a42dac2eaef2ab437',
    messagingSenderId: '1040924011798',
    projectId: 'laminas-swap',
    authDomain: 'laminas-swap.firebaseapp.com',
    storageBucket: 'laminas-swap.firebasestorage.app',
    measurementId: 'G-WWLVBMN4QT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrMAAbN9dp7DhMkHEByIVuE1Ywu6tohFk',
    appId: '1:1040924011798:ios:80f6e31ce3b278302ab437',
    messagingSenderId: '1040924011798',
    projectId: 'laminas-swap',
    storageBucket: 'laminas-swap.firebasestorage.app',
    iosBundleId: 'com.example.laminasSwap',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrMAAbN9dp7DhMkHEByIVuE1Ywu6tohFk',
    appId: '1:1040924011798:ios:80f6e31ce3b278302ab437',
    messagingSenderId: '1040924011798',
    projectId: 'laminas-swap',
    storageBucket: 'laminas-swap.firebasestorage.app',
    iosBundleId: 'com.example.laminasSwap',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ49YQFlJ1khgl1SCX3fSxdjDoc_rHFGo',
    appId: '1:1040924011798:android:51ed05b885d1e6f32ab437',
    messagingSenderId: '1040924011798',
    projectId: 'laminas-swap',
    storageBucket: 'laminas-swap.firebasestorage.app',
  );
}
